name: Conditional_Workflow.yml
run-name:  Testing if condition where any push happend in main branch

on:
  push:
    branches:
      - main
      - BLearn*
  pull_request:
    branches:
      - main
  fork:
    branches:
      - main


jobs:
  main_job:
    if: startsWith(github.ref, 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - run: echo "-------JOB EXECUTION ON MAIN BRANCH PUSH-------"
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: echo "TRIGGERED the main branch workflow - event based"


